/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package CRUD.Resultados;

import CRUD.Exames.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Caio
 */
public class ConsultarResultadoInterface extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarExameInterface
     */
    public ConsultarResultadoInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        idbusca = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID EXAME:");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Consultar Resultado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(idbusca, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idbusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ResultadosController resultadocontroller = new ResultadosController();
        Resultados resultado = resultadocontroller.consultarResultadoID(Integer.parseInt(this.idbusca.getText()));
        if (resultado != null) {
            ExameController examecontroller = new ExameController();
            Exame exame = examecontroller.consultarExameID(resultado.getId());
            if (exame.getTipo().equals("PRA")) {
                PRA resultadopra = resultadocontroller.consultarPRAID(resultado.getId());
                new PRAInterface(exame, resultadopra).setVisible(true);
            }
            else if (exame.getTipo().equals("HLA B27")) {
                HLA_B27 resultadob27 = resultadocontroller.consultarHLA_B27ID(resultado.getId());
                new HLA_B27Interface(exame, resultadob27).setVisible(true);
            } 
            else if (exame.getTipo().equals("CrossMatch")) {
                CrossMatch resultadocm = resultadocontroller.consultarCrossMatchID(resultado.getId());
                new CrossMatchInterface(exame, resultadocm).setVisible(true);
            } 
            else if (exame.getTipo().equals("Tipificação - C I - C II (Baixa / Media Resolução)")) {
                TipificacaoHLA resultadotipificacao = resultadocontroller.consultarTipificacaoID(resultado.getId());
                new TipificacaoHLAInterface(exame, resultadotipificacao, 0).setVisible(true);
            } 
            else if (exame.getTipo().equals("Tipificação - C I - C II (Alta Resolução)")) {
                TipificacaoHLA resultadotipificacao = resultadocontroller.consultarTipificacaoID(resultado.getId());
                new TipificacaoHLAInterface(exame, resultadotipificacao, 1).setVisible(true);
            } 
            else if (exame.getTipo().equals("Tipificação - C I  (Baixa / Media Resolução)")) {
                TipificacaoHLA resultadotipificacao = resultadocontroller.consultarTipificacaoID(resultado.getId());
                new TipificacaoHLAInterface(exame, resultadotipificacao, 2).setVisible(true);
            } 
            else if (exame.getTipo().equals("Tipificação - C II (Baixa / Media Resolução)")) {
                TipificacaoHLA resultadotipificacao = resultadocontroller.consultarTipificacaoID(resultado.getId());
                new TipificacaoHLAInterface(exame, resultadotipificacao, 3).setVisible(true);
            } 
            else if (exame.getTipo().equals("Tipificação - C I  (Alta Resolução)")) {
                TipificacaoHLA resultadotipificacao = resultadocontroller.consultarTipificacaoID(resultado.getId());
                new TipificacaoHLAInterface(exame, resultadotipificacao, 4).setVisible(true);
            } 
            else if (exame.getTipo().equals("Tipificação - C II (Alta Resolução)")) {
                TipificacaoHLA resultadotipificacao = resultadocontroller.consultarTipificacaoID(resultado.getId());
                new TipificacaoHLAInterface(exame, resultadotipificacao, 5).setVisible(true);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Resultado não encontrado!");
        }
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField idbusca;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
