/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CRUD.Materiais;

import javax.swing.JOptionPane;

/**
 *
 * @author Juliano
 */
public class CadastrarMaterial extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarMaterial
     */
    public CadastrarMaterial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t_header = new javax.swing.JLabel();
        t_modelo = new javax.swing.JLabel();
        t_nome = new javax.swing.JLabel();
        t_tipo = new javax.swing.JLabel();
        f_modelo = new javax.swing.JTextField();
        f_nome = new javax.swing.JTextField();
        t_fabricante = new javax.swing.JLabel();
        f_fabricante = new javax.swing.JTextField();
        t_quant = new javax.swing.JLabel();
        s_quant = new javax.swing.JSpinner();
        cb_tipo = new javax.swing.JComboBox();
        t_obs = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        f_obs = new javax.swing.JTextPane();
        b_cadastrar = new javax.swing.JButton();
        b_limpar = new javax.swing.JButton();
        b_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        t_header.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        t_header.setText("Cadastrar Material");

        t_modelo.setText("Modelo:");

        t_nome.setText("Nome:");

        t_tipo.setText("Tipo:");

        t_fabricante.setText("Fabricante:");

        t_quant.setText("Quantidade:");

        cb_tipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CrossMatch", "HLA B27", "PRA", "Tipificação - C I - C II (Baixa / Media Resolução)", "Tipificação - C I - C II (Alta Resolução)", "Tipificação - C I  (Baixa / Media Resolução)", "Tipificação - C I  (Alta Resolução)", "Tipificação - C II (Baixa / Media Resolução)", "Tipificação - C II (Alta Resolução)", "OUTROS" }));

        t_obs.setText("Observações:");

        jScrollPane1.setViewportView(f_obs);

        b_cadastrar.setText("Cadastrar");
        b_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cadastrarActionPerformed(evt);
            }
        });

        b_limpar.setText("Limpar");
        b_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_limparActionPerformed(evt);
            }
        });

        b_cancelar.setText("Cancelar");
        b_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b_cancelar)
                        .addGap(98, 98, 98)
                        .addComponent(b_limpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b_cadastrar))
                    .addComponent(jScrollPane1)
                    .addComponent(t_obs)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(t_nome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(f_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(t_modelo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(f_modelo))
                            .addComponent(t_header))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(t_fabricante)
                            .addComponent(t_quant))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(f_fabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s_quant, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(t_tipo)
                        .addGap(18, 18, 18)
                        .addComponent(cb_tipo, 0, 351, Short.MAX_VALUE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(t_header)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_modelo)
                    .addComponent(f_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_fabricante)
                    .addComponent(f_fabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_nome)
                    .addComponent(f_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_quant)
                    .addComponent(s_quant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_tipo)
                    .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(t_obs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_cadastrar)
                    .addComponent(b_limpar)
                    .addComponent(b_cancelar))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cadastrarActionPerformed
        String modelo, nome, fabricante, tipo, obs;
        int quant;
        
        modelo = f_modelo.getText();
        nome = f_nome.getText().toLowerCase();
        fabricante = f_fabricante.getText();
        System.out.println(modelo + nome + fabricante);
            if (MateriaisController.verificaCampos(modelo, nome, fabricante)){
                tipo = cb_tipo.getSelectedItem().toString();
                quant = (int) s_quant.getValue();
                obs = f_obs.getText();
                Materiais material = new Materiais(fabricante, nome, modelo, tipo, quant, obs, true);
                try {
                    MateriaisController.cadastrarMaterial(material);
                    JOptionPane.showMessageDialog(rootPane, "Material cadastrado com sucesso!");   
                    this.dispose();  
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "Nao foi possivel efetuar o cadastro!");
                }
                
            } else{
                JOptionPane.showMessageDialog(rootPane, "Todos os campos precisam ser preenchidos!");
            }   
    }//GEN-LAST:event_b_cadastrarActionPerformed

    private void b_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_limparActionPerformed
        this.f_fabricante.setText(" ");
        this.f_modelo.setText(" ");
        this.f_nome.setText(" ");
        this.s_quant.setValue(0);
        this.f_obs.setText(" ");
    }//GEN-LAST:event_b_limparActionPerformed

    private void b_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_b_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarMaterial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_cadastrar;
    private javax.swing.JButton b_cancelar;
    private javax.swing.JButton b_limpar;
    private javax.swing.JComboBox cb_tipo;
    private javax.swing.JTextField f_fabricante;
    private javax.swing.JTextField f_modelo;
    private javax.swing.JTextField f_nome;
    private javax.swing.JTextPane f_obs;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner s_quant;
    private javax.swing.JLabel t_fabricante;
    private javax.swing.JLabel t_header;
    private javax.swing.JLabel t_modelo;
    private javax.swing.JLabel t_nome;
    private javax.swing.JLabel t_obs;
    private javax.swing.JLabel t_quant;
    private javax.swing.JLabel t_tipo;
    // End of variables declaration//GEN-END:variables
}
