/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CRUD.Materiais;

import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juliano
 */
public class ConsultarMaterial extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarMaterial
     */
    public ConsultarMaterial() {
        initComponents();
        this.t_resultado.getColumnModel().getColumn(0);
        this.t_resultado.getColumnModel().getColumn(1);
        this.t_resultado.getColumnModel().getColumn(2);
        this.t_resultado.getColumnModel().getColumn(3);
        this.t_resultado.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t_header = new javax.swing.JLabel();
        rb_modelo = new javax.swing.JRadioButton();
        rb_fabricante = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        f_buscar = new javax.swing.JTextField();
        b_buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_resultado = new javax.swing.JTable();
        b_cancelar = new javax.swing.JButton();
        b_visualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        t_header.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        t_header.setText("Consultar Material");

        rb_modelo.setText("Modelo");
        rb_modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_modeloActionPerformed(evt);
            }
        });

        rb_fabricante.setText("Fabricante");
        rb_fabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_fabricanteActionPerformed(evt);
            }
        });

        jLabel1.setText("Buscar por:");

        f_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_buscarActionPerformed(evt);
            }
        });

        b_buscar.setText("Buscar");
        b_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_buscarActionPerformed(evt);
            }
        });

        t_resultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Modelo", "Nome", "Fabricante", "Quantidade"
            }
        ));
        jScrollPane1.setViewportView(t_resultado);

        b_cancelar.setText("Cancelar");
        b_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cancelarActionPerformed(evt);
            }
        });

        b_visualizar.setText("Visualizar");
        b_visualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_visualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(t_header)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb_modelo)
                            .addComponent(rb_fabricante)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(b_cancelar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b_visualizar))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(f_buscar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(b_buscar))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(t_header)
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_modelo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_fabricante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_buscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_cancelar)
                    .addComponent(b_visualizar))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb_modeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_modeloActionPerformed
        rb_fabricante.setSelected(false);
        rb_modelo.setSelected(true);
    }//GEN-LAST:event_rb_modeloActionPerformed

    private void rb_fabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_fabricanteActionPerformed
        rb_modelo.setSelected(false);
        rb_fabricante.setSelected(true);
    }//GEN-LAST:event_rb_fabricanteActionPerformed

    private void f_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_buscarActionPerformed
        
        
    }//GEN-LAST:event_f_buscarActionPerformed

    private void b_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_b_cancelarActionPerformed

    private void b_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_buscarActionPerformed
        String buscar;
        List lista = null;
        MateriaisController cont = new MateriaisController();
        Iterator it;
        Materiais material;
        DefaultTableModel tabela = (DefaultTableModel) this.t_resultado.getModel();
        
        try {
            buscar = f_buscar.getText();
            if (rb_modelo.isSelected()){
                lista = cont.buscarModelo(buscar);
            } else{
                lista = cont.buscarNome(buscar);
            }
            it = lista.iterator();
            limparTab();
            while (it.hasNext()){
                material = (Materiais) it.next();
                tabela.addRow(new Object[]{material.getModelo(), material.getNome(), material.getFabricante(), material.getQuantidade()});
            }    
        } catch (Exception e) {
            limparTab();
            JOptionPane.showMessageDialog(rootPane, "Resultado nao encontrado");
        }
        
    }//GEN-LAST:event_b_buscarActionPerformed

    private void b_visualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_visualizarActionPerformed
        String pos = this.t_resultado.getValueAt(this.t_resultado.getSelectedRow(), 0).toString();
        MateriaisController mat = new MateriaisController();
        Materiais material = mat.consultarMaterial(pos);
        new EditarMaterial(material).setVisible(true);
    }//GEN-LAST:event_b_visualizarActionPerformed

    private void limparTab(){
        DefaultTableModel tab = (DefaultTableModel) t_resultado.getModel();
        int quant;
        
        quant = this.t_resultado.getRowCount();
        for (int i=0; i < quant; i++) {
            tab.removeRow(0);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarMaterial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_buscar;
    private javax.swing.JButton b_cancelar;
    private javax.swing.JButton b_visualizar;
    private javax.swing.JTextField f_buscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rb_fabricante;
    private javax.swing.JRadioButton rb_modelo;
    private javax.swing.JLabel t_header;
    private javax.swing.JTable t_resultado;
    // End of variables declaration//GEN-END:variables
}
