/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package CRUD.Usuario;

/**
 *
 * @author Juliano
 */
public class PermissoesUsuario extends javax.swing.JDialog {

    private String permissoes = "";

    public String getPermissoes() {
        return this.permissoes;
    }

    public void setPermissoes(String permissoes) {
        this.permissoes = permissoes;
    }
    
    public PermissoesUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setModal(true);
    }
    
    public PermissoesUsuario(java.awt.Frame parent, boolean modal, Usuario user) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setModal(true);
        if (user != null){
            if (user.getPermissoes().equals("1 1 1 1 1 1 1 1 1")) {
                this.adm.setSelected(true);
            } else if (user.getPermissoes().equals("1 1 1 0 0 0 1 1 0")) {
                this.bio.setSelected(true);
            } else if (user.getPermissoes().equals("1 1 0 0 0 0 0 0 1")) {
                this.sec.setSelected(true);
            } else {
                MudarStatus(true);
                this.outro.setSelected(true);
                String[] perm = user.getPermissoes().split(" ");
                if (perm[0].equals("1")) {
                    this.pacientes.setSelected(true);
                } else {
                    this.pacientes.setSelected(false);
                }
                if (perm[1].equals("1")) {
                    this.exames.setSelected(true);
                } else {
                    this.exames.setSelected(false);
                }
                if (perm[2].equals("1")) {
                    this.resultados.setSelected(true);
                } else {
                    this.resultados.setSelected(false);
                }
                if (perm[3].equals("1")) {
                    this.usuarios.setSelected(true);
                } else {
                    this.usuarios.setSelected(false);
                }
                if (perm[4].equals("1")) {
                    this.relatorios.setSelected(true);
                } else {
                    this.relatorios.setSelected(false);
                }
                if (perm[5].equals("1")) {
                    this.compras.setSelected(true);
                } else {
                    this.compras.setSelected(false);
                }
                if (perm[6].equals("1")) {
                    this.equipamentos.setSelected(true);
                } else {
                    this.equipamentos.setSelected(false);
                }
                if (perm[7].equals("1")) {
                    this.estoque.setSelected(true);
                } else {
                    this.estoque.setSelected(false);
                }
                if (perm[8].equals("1")) {
                    this.pagamentos.setSelected(true);
                } else {
                    this.pagamentos.setSelected(false);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selecao = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox33 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        jCheckBox25 = new javax.swing.JCheckBox();
        jCheckBox26 = new javax.swing.JCheckBox();
        jCheckBox27 = new javax.swing.JCheckBox();
        jCheckBox28 = new javax.swing.JCheckBox();
        jCheckBox29 = new javax.swing.JCheckBox();
        adm = new javax.swing.JRadioButton();
        bio = new javax.swing.JRadioButton();
        sec = new javax.swing.JRadioButton();
        relatorios = new javax.swing.JCheckBox();
        pacientes = new javax.swing.JCheckBox();
        exames = new javax.swing.JCheckBox();
        resultados = new javax.swing.JCheckBox();
        usuarios = new javax.swing.JCheckBox();
        compras = new javax.swing.JCheckBox();
        equipamentos = new javax.swing.JCheckBox();
        estoque = new javax.swing.JCheckBox();
        outro = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jCheckBox32 = new javax.swing.JCheckBox();
        jCheckBox34 = new javax.swing.JCheckBox();
        jCheckBox35 = new javax.swing.JCheckBox();
        pagamentos = new javax.swing.JCheckBox();

        jLabel2.setText("jLabel2");

        jCheckBox33.setText("Pagamentos");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Permissões");

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Pacientes");
        jCheckBox1.setEnabled(false);

        jCheckBox2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox2.setSelected(true);
        jCheckBox2.setText("Exames");
        jCheckBox2.setEnabled(false);

        jCheckBox3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox3.setSelected(true);
        jCheckBox3.setText("Resultados");
        jCheckBox3.setEnabled(false);

        jCheckBox4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox4.setSelected(true);
        jCheckBox4.setText("Usuarios");
        jCheckBox4.setEnabled(false);

        jCheckBox5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox5.setSelected(true);
        jCheckBox5.setText("Compras");
        jCheckBox5.setEnabled(false);

        jCheckBox6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox6.setSelected(true);
        jCheckBox6.setText("Sala / Equipamentos");
        jCheckBox6.setEnabled(false);

        jCheckBox7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox7.setSelected(true);
        jCheckBox7.setText("Estoque");
        jCheckBox7.setEnabled(false);

        jCheckBox10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox10.setSelected(true);
        jCheckBox10.setText("Relatórios");
        jCheckBox10.setEnabled(false);

        jCheckBox12.setText("Relatórios");
        jCheckBox12.setEnabled(false);

        jCheckBox13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox13.setSelected(true);
        jCheckBox13.setText("Pacientes");
        jCheckBox13.setEnabled(false);

        jCheckBox14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox14.setSelected(true);
        jCheckBox14.setText("Exames");
        jCheckBox14.setEnabled(false);

        jCheckBox15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox15.setSelected(true);
        jCheckBox15.setText("Resultados");
        jCheckBox15.setEnabled(false);

        jCheckBox16.setText("Usuarios");
        jCheckBox16.setEnabled(false);

        jCheckBox17.setText("Compras");
        jCheckBox17.setEnabled(false);

        jCheckBox18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox18.setSelected(true);
        jCheckBox18.setText("Sala / Equipamentos");
        jCheckBox18.setEnabled(false);

        jCheckBox19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox19.setSelected(true);
        jCheckBox19.setText("Estoque");
        jCheckBox19.setEnabled(false);

        jCheckBox22.setText("Relatórios");
        jCheckBox22.setEnabled(false);

        jCheckBox23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox23.setSelected(true);
        jCheckBox23.setText("Pacientes");
        jCheckBox23.setEnabled(false);

        jCheckBox24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox24.setSelected(true);
        jCheckBox24.setText("Exames");
        jCheckBox24.setEnabled(false);

        jCheckBox25.setText("Resultados");
        jCheckBox25.setEnabled(false);

        jCheckBox26.setText("Usuarios");
        jCheckBox26.setEnabled(false);

        jCheckBox27.setText("Compras");
        jCheckBox27.setEnabled(false);

        jCheckBox28.setText("Sala / Equipamentos");
        jCheckBox28.setEnabled(false);

        jCheckBox29.setText("Estoque");
        jCheckBox29.setEnabled(false);

        selecao.add(adm);
        adm.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        adm.setText("Administrador");
        adm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admActionPerformed(evt);
            }
        });

        selecao.add(bio);
        bio.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bio.setText("Farmaceutico / Bioquímico");
        bio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bioActionPerformed(evt);
            }
        });

        selecao.add(sec);
        sec.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        sec.setText("Secretario(a)");
        sec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secActionPerformed(evt);
            }
        });

        relatorios.setText("Relatórios");
        relatorios.setEnabled(false);

        pacientes.setText("Pacientes");
        pacientes.setEnabled(false);

        exames.setText("Exames");
        exames.setEnabled(false);

        resultados.setText("Resultados");
        resultados.setEnabled(false);

        usuarios.setText("Usuarios");
        usuarios.setEnabled(false);

        compras.setText("Compras");
        compras.setEnabled(false);

        equipamentos.setText("Sala / Equipamentos");
        equipamentos.setEnabled(false);

        estoque.setText("Estoque");
        estoque.setEnabled(false);

        selecao.add(outro);
        outro.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        outro.setText("Outro");
        outro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outroActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jCheckBox32.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox32.setSelected(true);
        jCheckBox32.setText("Pagamentos");
        jCheckBox32.setEnabled(false);

        jCheckBox34.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox34.setSelected(true);
        jCheckBox34.setText("Pagamentos");
        jCheckBox34.setEnabled(false);

        jCheckBox35.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox35.setSelected(true);
        jCheckBox35.setText("Pagamentos");
        jCheckBox35.setEnabled(false);

        pagamentos.setText("Pagamentos");
        pagamentos.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(adm)
                        .addGap(68, 68, 68)
                        .addComponent(bio)
                        .addGap(37, 37, 37)
                        .addComponent(sec))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCheckBox1)
                                            .addComponent(jCheckBox2)
                                            .addComponent(jCheckBox3)
                                            .addComponent(jCheckBox4)
                                            .addComponent(jCheckBox10))
                                        .addGap(73, 73, 73)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jCheckBox7)
                                    .addComponent(jCheckBox6)
                                    .addComponent(jCheckBox5)
                                    .addComponent(jCheckBox32))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox13)
                                    .addComponent(jCheckBox14)
                                    .addComponent(jCheckBox15)
                                    .addComponent(jCheckBox16)
                                    .addComponent(jCheckBox19)
                                    .addComponent(jCheckBox18)
                                    .addComponent(jCheckBox17)
                                    .addComponent(jCheckBox12)
                                    .addComponent(jCheckBox34))
                                .addGap(56, 56, 56)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox23)
                                    .addComponent(jCheckBox24)
                                    .addComponent(jCheckBox25)
                                    .addComponent(jCheckBox26)
                                    .addComponent(jCheckBox29)
                                    .addComponent(jCheckBox28)
                                    .addComponent(jCheckBox27)
                                    .addComponent(jCheckBox22)
                                    .addComponent(jCheckBox35))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(194, 194, 194)
                                .addComponent(jButton2)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pacientes)
                    .addComponent(exames)
                    .addComponent(resultados)
                    .addComponent(usuarios)
                    .addComponent(relatorios)
                    .addComponent(outro)
                    .addComponent(estoque)
                    .addComponent(equipamentos)
                    .addComponent(compras)
                    .addComponent(pagamentos))
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addGap(344, 344, 344)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adm)
                    .addComponent(bio)
                    .addComponent(sec)
                    .addComponent(outro))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox7)
                        .addGap(2, 2, 2)
                        .addComponent(jCheckBox32))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBox13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox18)
                        .addGap(0, 0, 0)
                        .addComponent(jCheckBox19)
                        .addGap(2, 2, 2)
                        .addComponent(jCheckBox34))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBox23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox28)
                        .addGap(0, 0, 0)
                        .addComponent(jCheckBox29)
                        .addGap(2, 2, 2)
                        .addComponent(jCheckBox35))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pacientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exames)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resultados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usuarios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(relatorios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(compras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(equipamentos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(estoque)
                        .addGap(2, 2, 2)
                        .addComponent(pagamentos)))
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void secActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secActionPerformed
        if (!(this.outro.isSelected())){
            MudarStatus(false);
        }
    }//GEN-LAST:event_secActionPerformed

    private void outroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outroActionPerformed
        if (this.outro.isSelected()){
            MudarStatus(true);
        }
    }//GEN-LAST:event_outroActionPerformed

    private void admActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admActionPerformed
        if (!(this.outro.isSelected())){
            MudarStatus(false);
        }
    }//GEN-LAST:event_admActionPerformed

    private void bioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bioActionPerformed
        if (!(this.outro.isSelected())){
            MudarStatus(false);
        }
    }//GEN-LAST:event_bioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.permissoes = null;
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (this.adm.isSelected()){
            this.permissoes = "1 1 1 1 1 1 1 1 1";
            this.setVisible(false);
            this.dispose();
        }
        else if (this.bio.isSelected()){
            this.permissoes = "1 1 1 0 0 0 1 1 0";
            this.setVisible(false);
            this.dispose();
        }
        else if (this.sec.isSelected()){
            this.permissoes = "1 1 0 0 0 0 0 0 1";
            this.setVisible(false);
            this.dispose();
        }
        else if (this.outro.isSelected()){
            if (this.pacientes.isSelected()){
                this.permissoes += "1";
            }
            else{
                this.permissoes += "0";
            }
            if (this.exames.isSelected()){
                this.permissoes += " 1";
            }
            else{
                this.permissoes += " 0";
            }
            if (this.resultados.isSelected()){
                this.permissoes += " 1";
            }
            else{
                this.permissoes += " 0";
            }
            if (this.usuarios.isSelected()){
                this.permissoes += " 1";
            }
            else{
                this.permissoes += " 0";
            }
            if (this.relatorios.isSelected()){
                this.permissoes += " 1";
            }
            else{
                this.permissoes += " 0";
            }
            if (this.compras.isSelected()){
                this.permissoes += " 1";
            }
            else{
                this.permissoes += " 0";
            }
            if (this.equipamentos.isSelected()){
                this.permissoes += " 1";
            }
            else{
                this.permissoes += " 0";
            }
            if (this.estoque.isSelected()){
                this.permissoes += " 1";
            }
            else{
                this.permissoes += " 0";
            }
            if (this.pagamentos.isSelected()){
                this.permissoes += " 1";
            }
            else{
                this.permissoes += " 0";
            }
            this.setVisible(false);
            this.dispose();
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void MudarStatus(boolean valor){
        this.compras.setEnabled(valor);
        this.equipamentos.setEnabled(valor);
        this.estoque.setEnabled(valor);
        this.exames.setEnabled(valor);
        this.pacientes.setEnabled(valor);
        this.usuarios.setEnabled(valor);
        this.resultados.setEnabled(valor);
        this.relatorios.setEnabled(valor);
        this.pagamentos.setEnabled(valor);
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton adm;
    private javax.swing.JRadioButton bio;
    private javax.swing.JCheckBox compras;
    private javax.swing.JCheckBox equipamentos;
    private javax.swing.JCheckBox estoque;
    private javax.swing.JCheckBox exames;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox25;
    private javax.swing.JCheckBox jCheckBox26;
    private javax.swing.JCheckBox jCheckBox27;
    private javax.swing.JCheckBox jCheckBox28;
    private javax.swing.JCheckBox jCheckBox29;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox32;
    private javax.swing.JCheckBox jCheckBox33;
    private javax.swing.JCheckBox jCheckBox34;
    private javax.swing.JCheckBox jCheckBox35;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JRadioButton outro;
    private javax.swing.JCheckBox pacientes;
    private javax.swing.JCheckBox pagamentos;
    private javax.swing.JCheckBox relatorios;
    private javax.swing.JCheckBox resultados;
    private javax.swing.JRadioButton sec;
    private javax.swing.ButtonGroup selecao;
    private javax.swing.JCheckBox usuarios;
    // End of variables declaration//GEN-END:variables
}
